name: Coverage

on: workflow_dispatch

jobs:
  coverage:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create output directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path dist

      - name: Run test coverage
        shell: pwsh
        run: ./scripts/coverage.ps1
    