name: Integration Test

on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os_list: "ubuntu-latest"

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist

      - name: Check if sudo is executable
        run: |
          echo "Checking sudo binary:"
          file /usr/bin/sudo
          echo "Checking shared libraries:"
          ldd /usr/bin/sudo || echo "ldd not available or sudo is statically linked"
      - name: List dist folder
        run: ls -l ./dist

      - name: Install agent
        run: |
          sudo ./dist/rewst_agent_config.linux.bin --config-url ${{ vars.IT_CONFIG_URL }} --config-secret ${{ secrets.IT_CONFIG_SECRET }}= --org-id ${{ vars.IT_ORG_ID }}
