name: QA

on: workflow_dispatch

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml

  upload-assets:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: compiled-assets
          path: ${{ needs.build.outputs.binaries }}

