name: Sign

on: workflow_call

jobs:
  sign:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist

      - name: Batch sign code
        uses: sslcom/esigner-codesign@develop
        with:
          command: batch_sign
          username: ${{secrets.SSL_COM_USERNAME}}
          password: esignerDemo#1
          totp_secret: RDXYgV9qju+6/7GnMf1vCbKexXVJmUVr+86Wq/8aIGg=
          environment_name: "TEST"
          dir_path: ./dist
          output_path: ./signed

      - name: Upload signed assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-signed
          path: ./signed
