name: Sign

on: 
  workflow_call:
    secrets:
      ssl_com_username:
        required: true
      ssl_com_password:
        required: true
      ssl_com_credential_id:
        required: true
      ssl_com_totp_secret:
        required: true
      ssl_com_environment_name:
        required: true

jobs:
  sign:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist

      - name: Batch sign code
        uses: sslcom/esigner-codesign@develop
        with:
          command: batch_sign
          username: ${{ secrets.ssl_com_username }}
          password: ${{ secrets.ssl_com_password }}
          credential_id: ${{ secrets.ssl_com_credential_id }}
          totp_secret: ${{ secrets.ssl_com_totp_secret }}
          environment_name: ${{ secrets.ssl_com_environment_name }}
          dir_path: ./dist
          output_path: ./signed

      - name: Upload signed assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-signed
          path: ./signed
