name: Sign

on: workflow_call 

jobs:
  sign:
    strategy: 
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist

      - name: Download codesign tool
        shell: pwsh 
        run: |
          $downloadUrl = "${{ matrix.os == 'windows-latest' && 'https://www.ssl.com/download/codesigntool-for-windows/' || 'https://www.ssl.com/download/codesigntool-for-linux-and-macos/' }}"
          Invoke-WebRequest -Uri $downloadUrl -OutFile codesigntool.zip
          Expand-Archive -Path codesigntool.zip -DestinationPath .

      - name: Add execute permission on codesign
        shell: bash 
        if: matrix.os != 'windows-latest'
        run: chmod +x ./CodeSignTool.sh

      - name: Batch sign code
        run: |
          ${{ matrix.os == 'windows-latest' && './CodeSignTool.bat' || './CodeSignTool.sh'}} batch_sign -username="${{ secrets.SSL_COM_USERNAME }}" -password="${{ secrets.SSL_COM_PASSWORD }}" -credential_id="${{ secrets.SSL_COM_CREDENTIAL_ID }}" -totp_secret="${{ secrets.SSL_COM_OTP }}" -input_dir_path="./dist" -output_dir_path="./signed"

      - name: Upload signed assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-signed
          path: ./signed
