name: Sign

on: workflow_call

jobs:
  sign:
    strategy:
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download compiled binary
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sign binaries
        run: |
          Get-ChildItem .
          ./scripts/ssl_com_sign_binaries.ps1 -username '${{ secrets.SSL_COM_USERNAME }}' -password '${{ secrets.SSL_COM_PASSWORD }}' -credentialId '${{ secrets.SSL_COM_CREDENTIAL_ID }}' -totpSecret '${{ secrets.SSL_COM_OTP }}' -appDistPath "$((Get-Item .).FullName)\dist"

      - name: Upload signed assets
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-signed
          path: ./signed
