name: Staging

on: workflow_dispatch

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml

  sign:
    needs: build
    uses: ./.github/workflows/sign.yml
    
